services:
  base:
    build:
      dockerfile: ./Dockerfile
      target: base
      args:
        PHP_VERSION: 8.4
    environment:
      HOME_URL: http://localhost
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-project}
      MYSQL_USER: ${MYSQL_USER:-project}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-project}
      PHP_VERSION: 8.4
    volumes:
      - .:/app

  php:
    extends:
      service: base
    build:
      target: php
    volumes:
      - ~/.docker_cache/composer:/.composer/cache/
      - ~/.docker_cache/wp-cli:/.wp-cli/cache/

  fpm:
    extends:
      service: base
    build:
      target: fpm
    depends_on:
      - db

  server:
    extends:
      service: fpm
    build:
      target: server
    ports:
      - "80:80"
    volumes:
      - ./resources/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - fpm

  db:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-project}
      MYSQL_USER: ${MYSQL_USER:-project}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-project}
    ports:
      - "3306"

  installer:
    extends:
      service: php
    entrypoint: [ "install.sh" ]
