services:
  base:
    build:
      dockerfile: ./Dockerfile
      target: base
      args:
        PHP_VERSION: 8.4
    environment:
      HOME_URL: http://localhost
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-project}
      MYSQL_USER: ${MYSQL_USER:-project}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-project}
      PHP_VERSION: 8.4
      PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE:-off}
      ASAAS_API_KEY: ${ASAAS_API_KEY:-}
    extra_hosts:
      - "host.docker.internal:${HOST_DOCKER_INTERNAL_IP:-172.17.0.1}"
    volumes:
      - .:/app
      - ./plugin:/app/public/packages/plugins/curso-php-conference-2025

  php:
    extends:
      service: base
    build:
      target: php
    volumes:
      - ~/.docker_cache/composer:/.composer/cache/
      - ~/.docker_cache/wp-cli:/.wp-cli/cache/
      - ./.config/chromium:/.config/chromium
      - ./tests/db.php:/app/public/packages/db.php

  fpm:
    extends:
      service: base
    build:
      target: fpm
    depends_on:
      - db

  server:
    extends:
      service: fpm
    build:
      target: server
    ports:
      - "80:80"
    volumes:
      - ./resources/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - fpm

  db:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-project}
      MYSQL_USER: ${MYSQL_USER:-project}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-project}
    ports:
      - "3306"

  installer:
    extends:
      service: php
    entrypoint: [ "install.sh" ]

  node:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ~/.docker_cache/npm:/.npm
    environment:
      - npm_config_cache=/.npm
